/*
Package main is an example of the simplest goaction script.

Notice that the only non-generated file is ./main.go.
The generated files were generated using Github action ./github/workflows/goaction.yml.

The ./main.go is the only non-generated file and is a simple Go script, and can be run with:

	$ go run .

The ./action.yml is autogenerated and contains the action definition. Notice that the flag from the
program below appears as the input for the Github action. You can see the action in-action in the
(action page) https://github.com/posener/goaction-example/actions?query=workflow%%3A.github%%2Fworkflows%%2Fgoaction.yml.

The ./Dockerfile is autogenerated and will also run the ./main.go sctipt. You can build and run it
with docker, even if you don't have Go installed on your machine:

	$ docker build -t goaction-example .
	$ docker run --rm goaction-example

This is the simplest program possible. Goaction also provides a library that helps writing Github
action scripts easily.
*/
package main

import (
	"flag"
	"log"
)

var who = flag.String("who", "world", "Say hello to who")

func main() {
	flag.Parse()
	log.Println("Hello,", *who)
}
