on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  goaction:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Update action files
      uses: posener/goaction@v1
      with:
        path: main.go
        github-token: '${{ secrets.GITHUB_TOKEN }}'
    - name: Example
      uses: ./
      with:
        who: me